language: node_js
cache: yarn
node_js:
  - "8"

script:
  - yarn lint
  - yarn test
  - REACT_APP_PUBLIC_URL=/brush-strokes-frontend/ yarn build

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: build/
    github_token: $GITHUB_TOKEN
    on:
      tags: true
